---
language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
    - pip install boto3
    - pip install utils
    - pip install moto
    - pip install coverage
    - pip install mock
    - pip install pytest
    - pip install psycopg2
    - pip install google_compute_engine
branches:
    only:
        - master
        - develop
addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"
script:
    - coverage erase
    - coverage run -m pytest tests/test_bucket_event_lambda.py
    - coverage xml -i
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
